### ISSUE TITLE
Sidekiq will not load

### ISSUE THREAD

**Issue by rhuppert** [peterkeen/payola#121]
After installing Payola in my app, starting Sidekiq bombs out:
```
$ bundle exec sidekiq -q mailer - q default
uninitialized constant ApplicationHelper
/home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/payola-payments-1.3.1/app/mailers/payola/receipt_mailer.rb:3:in `<class:ReceiptMailer>'
/home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/payola-payments-1.3.1/app/mailers/payola/receipt_mailer.rb:2:in `<module:Payola>'
/home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/payola-payments-1.3.1/app/mailers/payola/receipt_mailer.rb:1:in `<top (required)>'
/home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
```
I have copied the mailers to /app/views/payola/receipt_mailer/..
Also added to payola.rb
```
config.secret_key = ENV["STRIPE_SECRET_KEY"]
config.publishable_key = ENV["STRIPE_PUBLISHABLE_KEY"]
config.background_worker = :sidekiq
config.send_email_for :receipt
```
I'm a bit at a loss and not clear how to resolve the uninitialized constant error.
```
module Payola
  class ReceiptMailer < ActionMailer::Base
    add_template_helper ::ApplicationHelper
    helper Payola::PriceHelper
```
I suspect I may have missed some configuration issue, but I've been through the docs and don't see it. My application is subscription only, with no one time sales.

**Comment by rhuppert** [comment]
I'm really not sure if this belongs here as a Github issue and have moved it plus another comment to the Google group. https://groups.google.com/forum/#!topic/payola-payments/uXRwW1BSogE
