### ISSUE TITLE
Cant find stripe_id after creating a subscription.

### ISSUE THREAD

**Issue by stevendelarwelle** [peterkeen/payola#149]
All webhooks prior to this were successful. Up to this point then no dice. Any ideas?

Heres the part of the log:
```
2015-07-23T18:25:34.989394+00:00 app[web.1]:   Parameters: {"guid"=>"e90r4o"}
2015-07-23T18:25:35.002915+00:00 app[web.1]:   Payola::Affiliate Load (2.4ms)  SELECT  "payola_affiliates".* FROM "payola_affiliates" WHERE (lower(code) = lower(NULL))  ORDER BY "payola_affiliates"."id" ASC LIMIT 1
2015-07-23T18:25:35.015547+00:00 app[web.1]: Completed 200 OK in 26ms (Views: 0.4ms | ActiveRecord: 9.7ms)
2015-07-23T18:25:34.982176+00:00 app[web.1]: Started GET "/payola/subscription_status/e90r4o" for 64.73.118.1 at 2015-07-23 18:25:34 +0000
2015-07-23T18:25:35.011022+00:00 app[web.1]:   Payola::Subscription Load (7.3ms)  SELECT  "payola_subscriptions".* FROM "payola_subscriptions" WHERE "payola_subscriptions"."guid" = $1 LIMIT 1  [["guid", "e90r4o"]]
2015-07-23T18:25:35.015669+00:00 heroku[router]: at=info method=GET path="/payola/subscription_status/e90r4o" host=www.trakapp.com request_id=4d436fd9-0a94-4782-9b45-0e7ce84751da fwd="64.73.118.1" dyno=web.1 connect=3ms service=552ms status=304
bytes=442
2015-07-23T18:25:35.613851+00:00 heroku[router]: at=info method=GET path="/payola/subscription_status/e90r4o" host=www.trakapp.com request_id=d9d8fb80-45cf-4a46-aa04-07f3c81b3b93 fwd="64.73.118.1" dyno=web.1 connect=2ms service=59ms status=304 b
ytes=442
2015-07-23T18:25:35.562741+00:00 app[web.1]: Started GET "/payola/subscription_status/e90r4o" for 64.73.118.1 at 2015-07-23 18:25:35 +0000
2015-07-23T18:25:35.614366+00:00 app[web.1]:   Payola::Subscription Load (2.2ms)  SELECT  "payola_subscriptions".* FROM "payola_subscriptions" WHERE "payola_subscriptions"."guid" = $1 LIMIT 1  [["guid", "e90r4o"]]
2015-07-23T18:25:35.594171+00:00 app[web.1]: Processing by Payola::SubscriptionsController#status as */*
2015-07-23T18:25:35.594193+00:00 app[web.1]:   Parameters: {"guid"=>"e90r4o"}
2015-07-23T18:25:35.611066+00:00 app[web.1]:   Payola::Affiliate Load (15.9ms)  SELECT  "payola_affiliates".* FROM "payola_affiliates" WHERE (lower(code) = lower(NULL))  ORDER BY "payola_affiliates"."id" ASC LIMIT 1
2015-07-23T18:25:35.615643+00:00 app[web.1]: Completed 200 OK in 21ms (Views: 0.3ms | ActiveRecord: 18.1ms)
2015-07-23T18:25:35.937374+00:00 app[worker.1]:   Delayed::Backend::ActiveRecord::Job Load (1.9ms)  UPDATE "delayed_jobs" SET locked_at = '2015-07-23 18:25:35.934831', locked_by = 'host:a05093de-58d5-406f-a70b-64b728e9dc87 pid:3' WHERE id IN (SE
LECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-07-23 18:25:35.934118' AND (locked_at IS NULL OR locked_at < '2015-07-23 14:25:35.934167') OR locked_by = 'host:a05093de-58d5-406f-a70b-64b728e9dc87 pid:3') AND failed_at IS N
ULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2015-07-23T18:25:36.195556+00:00 heroku[router]: at=info method=GET path="/payola/subscription_status/e90r4o" host=www.trakapp.com request_id=23a577ba-1e50-4ceb-8b28-6c2b9ee2c087 fwd="64.73.118.1" dyno=web.1 connect=1ms service=43ms status=304 b
ytes=442
2015-07-23T18:25:36.167277+00:00 app[web.1]: Started GET "/payola/subscription_status/e90r4o" for 64.73.118.1 at 2015-07-23 18:25:36 +0000
2015-07-23T18:25:36.190016+00:00 app[web.1]:   Payola::Subscription Load (5.1ms)  SELECT  "payola_subscriptions".* FROM "payola_subscriptions" WHERE "payola_subscriptions"."guid" = $1 LIMIT 1  [["guid", "e90r4o"]]
2015-07-23T18:25:36.179476+00:00 app[web.1]: Processing by Payola::SubscriptionsController#status as */*
2015-07-23T18:25:36.179540+00:00 app[web.1]:   Parameters: {"guid"=>"e90r4o"}
2015-07-23T18:25:36.184044+00:00 app[web.1]:   Payola::Affiliate Load (3.4ms)  SELECT  "payola_affiliates".* FROM "payola_affiliates" WHERE (lower(code) = lower(NULL))  ORDER BY "payola_affiliates"."id" ASC LIMIT 1
2015-07-23T18:25:36.193010+00:00 app[web.1]: Completed 200 OK in 13ms (Views: 0.3ms | ActiveRecord: 8.5ms)
2015-07-23T18:25:36.620755+00:00 app[web.1]: Started POST "/payola/events" for 54.241.31.99 at 2015-07-23 18:25:36 +0000
2015-07-23T18:25:36.626896+00:00 app[web.1]:   Parameters: {"id"=>"evt_16RoNqETlKzs8qLqdF3d9u01", "created"=>1437675930, "livemode"=>false, "type"=>"invoice.payment_succeeded", "data"=>{"object"=>{"date"=>1437675930, "id"=>"in_16RoNqETlKzs8qLqHk
tUQ6AL", "period_start"=>1437675930, "period_end"=>1437675930, "lines"=>{"object"=>"list", "total_count"=>1, "has_more"=>false, "url"=>"/v1/invoices/in_16RoNqETlKzs8qLqHktUQ6AL/lines", "data"=>[{"id"=>"sub_6f8f9lnFysfZNV", "object"=>"line_item",
 "type"=>"subscription", "livemode"=>false, "amount"=>2000, "currency"=>"usd", "proration"=>false, "period"=>{"start"=>1437675930, "end"=>1440354330}, "subscription"=>nil, "quantity"=>1, "plan"=>{"interval"=>"month", "name"=>"Plus", "created"=>1
435715870, "amount"=>2000, "currency"=>"usd", "id"=>"plus20", "object"=>"plan", "livemode"=>false, "interval_count"=>1, "trial_period_days"=>nil, "metadata"=>{}, "statement_descriptor"=>nil}, "description"=>nil, "discountable"=>true, "metadata"=
>{}}]}, "subtotal"=>2000, "total"=>2000, "customer"=>"cus_6f8fbpL7bHMywI", "object"=>"invoice", "attempted"=>true, "closed"=>true, "forgiven"=>false, "paid"=>true, "livemode"=>false, "attempt_count"=>1, "amount_due"=>2000, "currency"=>"usd", "st
arting_balance"=>0, "ending_balance"=>0, "next_payment_attempt"=>nil, "webhooks_delivered_at"=>nil, "charge"=>"ch_16RoNqETlKzs8qLqsos0SRXp", "discount"=>nil, "application_fee"=>nil, "subscription"=>"sub_6f8f9lnFysfZNV", "tax_percent"=>nil, "tax"
=>nil, "metadata"=>{}, "statement_descriptor"=>nil, "description"=>nil, "receipt_number"=>nil}}, "object"=>"event", "pending_webhooks"=>1, "request"=>"req_6f8f0eaxSGUyie", "api_version"=>"2015-02-18", "webhook"=>{"id"=>"evt_16RoNqETlKzs8qLqdF3d9
u01", "created"=>1437675930, "livemode"=>false, "type"=>"invoice.payment_succeeded", "data"=>{"object"=>{"date"=>1437675930, "id"=>"in_16RoNqETlKzs8qLqHktUQ6AL", "period_start"=>1437675930, "period_end"=>1437675930, "lines"=>{"object"=>"list", "
total_count"=>1, "has_more"=>false, "url"=>"/v1/invoices/in_16RoNqETlKzs8qLqHktUQ6AL/lines", "data"=>[{"id"=>"sub_6f8f9lnFysfZNV", "object"=>"line_item", "type"=>"subscription", "livemode"=>false, "amount"=>2000, "currency"=>"usd", "proration"=>
false, "period"=>{"start"=>1437675930, "end"=>1440354330}, "subscription"=>nil, "quantity"=>1, "plan"=>{"interval"=>"month", "name"=>"Plus", "created"=>1435715870, "amount"=>2000, "currency"=>"usd", "id"=>"plus20", "object"=>"plan", "livemode"=>
false, "interval_count"=>1, "trial_period_days"=>nil, "metadata"=>{}, "statement_descriptor"=>nil}, "description"=>nil, "discountable"=>true, "metadata"=>{}}]}, "subtotal"=>2000, "total"=>2000, "customer"=>"cus_6f8fbpL7bHMywI", "object"=>"invoic
e", "attempted"=>true, "closed"=>true, "forgiven"=>false, "paid"=>true, "livemode"=>false, "attempt_count"=>1, "amount_due"=>2000, "currency"=>"usd", "starting_balance"=>0, "ending_balance"=>0, "next_payment_attempt"=>nil, "webhooks_delivered_at
"=>nil, "charge"=>"ch_16RoNqETlKzs8qLqsos0SRXp", "discount"=>nil, "application_fee"=>nil, "subscription"=>"sub_6f8f9lnFysfZNV", "tax_percent"=>nil, "tax"=>nil, "metadata"=>{}, "statement_descriptor"=>nil, "description"=>nil, "receipt_number"=>ni
l}}, "object"=>"event", "pending_webhooks"=>1, "request"=>"req_6f8f0eaxSGUyie", "api_version"=>"2015-02-18"}}
2015-07-23T18:25:36.639938+00:00 app[web.1]:    (3.0ms)  BEGIN
2015-07-23T18:25:36.647973+00:00 app[web.1]:   SQL (2.7ms)  INSERT INTO "payola_stripe_webhooks" ("stripe_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["stripe_id", "evt_16RoNqETlKzs8qLqdF3d9u01"], ["created_at", "2015-0
7-23 18:25:36.644134"], ["updated_at", "2015-07-23 18:25:36.644134"]]
2015-07-23T18:25:36.625516+00:00 app[web.1]: Processing by StripeEvent::WebhookController#event as XML
2015-07-23T18:25:36.636058+00:00 app[web.1]:   Payola::StripeWebhook Exists (5.2ms)  SELECT  1 AS one FROM "payola_stripe_webhooks" WHERE "payola_stripe_webhooks"."stripe_id" = $1 LIMIT 1  [["stripe_id", "evt_16RoNqETlKzs8qLqdF3d9u01"]]
2015-07-23T18:25:36.643949+00:00 app[web.1]:   Payola::StripeWebhook Exists (2.8ms)  SELECT  1 AS one FROM "payola_stripe_webhooks" WHERE "payola_stripe_webhooks"."stripe_id" = 'evt_16RoNqETlKzs8qLqdF3d9u01' LIMIT 1
2015-07-23T18:25:36.659314+00:00 app[web.1]:    (10.6ms)  COMMIT
2015-07-23T18:25:37.146912+00:00 app[web.1]:   Payola::Subscription Load (12.5ms)  SELECT  "payola_subscriptions".* FROM "payola_subscriptions" WHERE "payola_subscriptions"."stripe_id" = $1 LIMIT 1  [["stripe_id", "sub_6f8f9lnFysfZNV"]]
2015-07-23T18:25:37.231104+00:00 app[web.1]:
2015-07-23T18:25:37.231110+00:00 app[web.1]: ActiveRecord::RecordNotFound (Couldn't find Payola::Subscription):
2015-07-23T18:25:37.231112+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/core.rb:195:in `find_by!'
2015-07-23T18:25:37.231115+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/payola-payments-1.3.1/app/services/payola/invoice_behavior.rb:13:in `create_sale_from_event'
2015-07-23T18:25:37.231116+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/payola-payments-1.3.1/app/services/payola/invoice_paid.rb:6:in `call'
2015-07-23T18:25:37.231117+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/stripe_event-1.5.0/lib/stripe_event.rb:62:in `call'
```

**Comment by stevendelarwelle** [comment]
Found the issue, it was bombing on the active job sending emails. "I'm Stupid" :-1:

**Comment by peterkeen** [comment]
No worries. Thanks for updating!
