### ISSUE TITLE
can't pass env variables

### ISSUE THREAD

**Issue by alfredoreduarte** [peterkeen/payola#268]
Hi! Whenever I try to create a plan, this is what I get:

```
SubscriptionPlan.create(name: "Basic Development", stripe_id: "basic_development", amount: 29000, interval: "month", trial_period_days: 0)
   (0.2ms)  BEGIN
  SubscriptionPlan Exists (0.5ms)  SELECT  1 AS one FROM "subscription_plans" WHERE "subscription_plans"."stripe_id" = $1 LIMIT $2  [["stripe_id", "basic_development"], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
TypeError: normalize_opts expects a string or a hash
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/bundler/gems/stripe-ruby-2de99c55ceef/lib/stripe/util.rb:203:in `normalize_opts'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/bundler/gems/stripe-ruby-2de99c55ceef/lib/stripe/api_resource.rb:62:in `retrieve'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/payola-payments-1.5.0/app/services/payola/create_plan.rb:7:in `call'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/payola-payments-1.5.0/app/models/concerns/payola/plan.rb:24:in `create_stripe_plan'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:770:in `block (2 levels) in deprecated_false_terminator'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:769:in `catch'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:769:in `block in deprecated_false_terminator'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:302:in `_create_record'
... 26 levels...
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/alfredo/Websites/ita-api/bin/rails:9:in `<top (required)>'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/alfredo/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/alfredo/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/alfredo/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

After digging around some of the code, it seems like they keys aren't being properly set or handled. I've already tried setting the keys in almost every way possible:

With an .env file (using heroku-local)
```
STRIPE_SECRET_KEY=xxx
STRIPE_PUBLISHABLE_KEY=xxx
```

Reading the env variables inside the initializer
```
Payola.configure do |config|
	config.secret_key = ENV["STRIPE_SECRET_KEY"]
	config.publishable_key = ENV["STRIPE_PUBLISHABLE_KEY"]
end
```

Setting the values directly at the initializer
```
Payola.configure do |config|
	config.secret_key = "xxx"
	config.publishable_key = "xxx"
end
```

Am I missing something?

**Comment by eliotsykes** [comment]
Hi @alfredoreduarte! It *might* be that the initializer and environment changes aren't getting picked up if the Spring application preloader isn't getting restarted. Check the new Debugging page on the wiki for further info: https://github.com/peterkeen/payola/wiki/Debugging

**Comment by alfredoreduarte** [comment]
That fixed it. Thanks!

**Comment by eliotsykes** [comment]
That's good to hear, thanks for the update and closing the issue! 😃
